### ISSUE TITLE
Filter support

### ISSUE THREAD

**Issue by 112batman** [Cog-Creators/Lavalink-Jars#5]
Will this support builds of the dev branch, or include filter support?

**Comment by Drapersniper** [comment]
These JARs will in the future have filter support, that being said it won't necesarelly support builds from freds dev branch.

**Comment by 112batman** [comment]
Ok... Any chance I can use the arm64 natives from this jar to build my own jar of the dev branch?

**Comment by 112batman** [comment]
@Drapersniper

**Comment by aikaterna** [comment]
Hey there. You are free to take natives from this if you wish but it may not be as simple as you're expecting - the filters have their own native files along with just about everything else in the dependency chain. We will be releasing a fully featured, filter-enabled jar when we get to it - there's a lot of moving parts here and since this version supports nonstandard architectures like ARM and possibly mac M1 in the future there's a bit of work to do before it will be ready. We're also working on enabling JDA-NAS on all devices if it's feasable. When that next version is ready, you will see mentions of the features in the description of the release we publish.
