### ISSUE TITLE
Issue: Change server endpoint while playing music

### ISSUE THREAD

**Issue by LukazyOne** [Cog-Creators/Lavalink-Jars#6]
If I change the server region of the voice chat, the bot no longer plays the music.

**Comment by aikaterna** [comment]
Please open an issue on the actual repository for Lavalink if there's not one open in the issues: https://github.com/Freyacodes/Lavalink. This issue was also mentioned previously in the #lavalink channel in the JDA server, so if you need more immediate support, go there or speak with the maintainers of the library you use to interface with the Lavalink.jar as it could be resolved that way as well.
